
--	Kategorilere ayirarak satis rakamlarını getirme
SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,SUM(TOTALPRICE) FROM SALES 
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4 ORDER BY SUM(TOTALPRICE) DESC

--Magazalarin musteri sayilarini getirme(tekil müşteri);
SELECT CITY, COUNT(DISTINCT CUSTOMERCODE) AS SINGLECUSTOMERS FROM SALES 
GROUP BY CITY ORDER BY COUNT(DISTINCT CUSTOMERCODE) DESC

-- 40.000 tl Cironun üzerinde satış yapan mağazaları getiren sorgu;
SELECT CITY ,SUM(TOTALPRICE) AS TOTALPRICEE FROM SALES  
GROUP BY CITY HAVING SUM(TOTALPRICE)>40000 ORDER BY SUM(TOTALPRICE) DESC

