SELECT IT.CATEGORY1, IT.CATEGORY2, SUM(OD.LINETOTAL) AS TOPLAMSIPARISTUTARI,
SUM(OD.AMOUNT) AS MIKTAR,
COUNT(OD.ID)AS TOPLAMSÝPARIS

FROM ORDERS O
INNER JOIN  USERS U ON U.ID=O.USERID
INNER JOIN  ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN INVOICES F ON O.ID=F.ORDERID
INNER JOIN CITIES C ON C.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.TOWNID
INNER JOIN PAYMENTS P ON O.ID=P.ORDERID 
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID


GROUP BY IT.CATEGORY1,IT.CATEGORY2
ORDER BY 4 DESC