
SELECT U.USERNAME_ AS KULLANICIADI,U.NAMESURNAME AS ADSOYAD,C.CITY AS ÝL,T.TOWN AS ÝLÇE,
D.DISTRICT AS ÝLÇE,A.ADDRESSTEXT AS AÇIKADRES,O.ID AS SÝPARÝÞNO,O.DATE_ AS TARÝH,
O.TOTALPRICE AS TOPLAMTUTAR,P.DATE_ AS ÖDEMETARIHI,P.APPROVECODE AS ONAYKODU,
F.DATE_ AS FATURATARÝHÝ,F.CARGOFICHENO AS KARGOFÝÞNO

FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES C ON C.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES F ON F.ORDERID = O.ID



