--JOIN KULLANARAK 2 TABLO BÝRLEÞTÝRME VE HANGÝ ÞEHÝRLERDE KAÇ KULLANICI VAR SORGUSU
SELECT
CT.CITY,COUNT(U.ID)
FROM USERS U

JOIN ADDRESS A ON U.ID = A.USERID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID

GROUP BY CT.CITY

