--CASE WHEN YAPISI(OLMAYAN BÝR SÜTÜN YARATMAK)

SELECT PAYMENTTYPE AS ODEMETURU,
CASE
	WHEN PAYMENTTYPE=1 THEN 'KREDÝ KARTI'
	WHEN PAYMENTTYPE=2 THEN 'BANKA HAVALESÝ'
	END AS ODEMETURU_ACIKLAMA,
SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS

GROUP BY PAYMENTTYPE